# fly.toml app configuration file generated for meetups-calendar on 2024-04-10T17:19:25-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'meetups-calendar'
primary_region = 'yul'

[env]
  JAVA_OPTS = "-Xmx250M -XX:MaxMetaspaceSize=50M -XX:ReservedCodeCacheSize=50M"
  BPL_JVM_THREAD_COUNT = 25

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  man_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-2x'


[build]
builder = "paketobuildpacks/builder-jammy-tiny"
#buildpacks = ["gcr.io/paketo-buildpacks/java"]


[build.args]
#BP_NATIVE_IMAGE="true"
BP_JVM_CDS_ENABLED="true"
#BP_SPRING_AOT_ENABLED="true"
BP_JVM_VERSION="21"
#JAVA_TOOL_OPTIONS='-XX:ActiveProcessorCount=-1'
CDS_TRAINING_JAVA_TOOL_OPTIONS="-Dspring.jpa.hibernate.ddl-auto=none -Dhibernate.dialect=org.hibernate.dialect.PostgreSQLDialect"
#BP_GRADLE_BUILD_ARGUMENTS="--no-daemon -Dorg.gradle.welcome=never -x collectReachabilityMetadata assemble"
