name: Trigger auto deployment for meetups-calendar

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/meetups-calendar-AutoDeployTrigger-ace42f47-355b-41c4-a0dc-ba25dff9ff44.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MEETUPSCALENDAR_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MEETUPSCALENDAR_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MEETUPSCALENDAR_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.MEETUPSCALENDAR_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MEETUPSCALENDAR_REGISTRY_PASSWORD }}
          containerAppName: meetups-calendar
          resourceGroup: anthony-resource-group
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


